#https://docs.docker.com/engine/reference/builder/

- là 1 file dạng text, không có đuôi mở rộng, nếu có thì xóa
- chứa đặc tả về một trừng thực thi phần mềm, cấu trúc cho docker image 
=> build ra docker image dung lượng từ vài mb đến gb
- cú pháp build ra image: "docker build -t getting-started ." trong đó 

1. trong dockerfile:

 # syntax=docker/dockerfile:1
 FROM node:12-alpine
 RUN apk add --no-cache python g++ make
 WORKDIR /app
 COPY . .
 RUN yarn install --production
 CMD ["node", "src/index.js"]

2. cú pháp
cú pháp chung có dạng: INSTRUCTION (viết hoa, chỉ thị) argument (nội dung của chỉ thị)
ở trên chỉ thị bắt buộc phải bắt đầu bằng FROM để khai báo đâu là image được sử dụng để làm nền xây dựng lên image
3.giải thích
This command used the Dockerfile to build a new container image.
 You might have noticed that a lot of “layers” were downloaded.
 This is because we instructed the builder that we wanted to start from the node:12-alpine image.
 But, since we didn’t have that on our machine, that image needed to be downloaded.

After the image was downloaded,
 we copied in our application and used yarn to install our application’s dependencies.
 The CMD directive specifies the default command to run when starting a container from this image.

Finally, the -t flag tags our image.
 Think of this simply as a human-readable name for the final image.
 Since we named the image getting-started, we can refer to that image when we run a container.

The . at the end of the docker build command tells that Docker should look for the Dockerfile
in the current directory.

**************
1. docker build -f [path to docker file] -t [đường dẫn cho image/tên image]:[tag(v1)]