version: '3.4'

services:
# DATABASE SERVICES
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

# ASP.NET SERVICES
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
# OTHER SERVICES
  portainer:
    image: portainer/portainer-ce

  mongoclient:
    image: mongoclient/mongoclient

  pgadmin:
    image: dpage/pgadmin4



volumes:
  mongo_data:
  postgres_data:
  portainer_data:
  pgadmin_data:


